version: 2
registries:
    github:
        type: git
        url: https://github.com
        username: x-access-token
        password: ${{secrets.SHIMMER_ACCESS_TOKEN}}
updates:
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
