default_root_dir: "/home/benjamin/Projects/simple-shapes-dataset/checkpoints"

dataset:
    # path: "/home/benjamin/Projects/simple-shapes-dataset/sample_dataset"
    path: "/mnt/SSD/datasets/simple_shapes_dataset"

wandb: 
    enabled: true
    save_dir: "/mnt/SSD/benjamin/wandb/shimmer-ssd"
    project: "shimmer-simple-shapes"
    entity: "vanrullen-lab"
    reinit: true

visualization:
    explore_vae:
        checkpoint: ${default_root_dir}/qjjpwi2z/epoch=96.ckpt
