training:
    optim:
        lr: 4e-3
        weight_decay: 1e-6
        max_lr: 3e-3
        start_lr: 8e-4
        end_lr: 1e-3
        pct_start: 0.1

    max_steps: 300000

logging:
    log_val_medias_every_n_epochs: 50
    log_train_medias_every_n_epochs: 50
    filter_images:
        - pred_trans_attr_to_attr
        - pred_trans_v_latents_to_v_latents
        - pred_trans_t_to_t
        - pred_trans_attr_to_v_latents
        - pred_trans_attr_to_t
        - pred_trans_t_to_v_latents
        - pred_trans_t_to_attr
        - pred_trans_v_latents_to_attr
        - pred_trans_v_latents_to_t
        - pred_cycle_v_latents_to_attr
        - pred_cycle_v_latents_to_t
        - pred_cycle_t_to_attr
        - pred_cycle_t_to_v_latents
        - pred_cycle_attr_to_v_latents
        - pred_cycle_attr_to_t

domains:
    - checkpoint_path: "#{default_root_dir}/checkpoints/pretrained/domain_attr.ckpt"
      domain_type: attr
      args:
          n_unpaired: "#{domain_data_args.attr.n_unpaired}"
    - checkpoint_path: "#{default_root_dir}/pretrained/domain_v.ckpt"
      domain_type: v_latents

domain_data_args:
    v_latents:
        presaved_path: vae_v_shimmer.npy
    attr:
        n_unpaired: 0

domain_proportions: 
    -   domains: ["attr"]
        proportion: 1.0
    -   domains: ["v"]
        proportion: 1.0
    -   domains: ["v", "attr"]
        proportion: 1.0
