global_workspace:
    domain_proportions: 
        -   domains: ["v"]
            proportion: 1.0
        -   domains: ["attr"]
            proportion: 1.0
        -   domains: ["v", "attr"]
            proportion: 0.001

