global_workspace:
    domain_proportions: 
        -   domains: ["v"]
            proportion: 1.0
        -   domains: ["attr"]
            proportion: 1.0
        -   domains: ["v", "attr"]
            proportion: 0.001

logging:
    log_val_medias_every_n_epochs: 10
    log_train_medias_every_n_epochs: 10
